baseURL = 'https://www.goodjobsoftware.ca/'
languageCode = 'en-us'
title = 'Josh Reynolds'
theme = 'PaperMod'

[services.googleAnalytics]
  ID = "G-WMD04PCS93"

[params]
  favicon = "/favicon.svg"

[params.profileMode]
  enabled = true
  title = "Josh Reynolds"
  subtitle = "Engineering Leader & Systems Thinker"
  imageUrl = "/images/profile.webp"
  imageTitle = "Josh Reynolds"
  imageWidth = 400
  imageHeight = 400

[[params.socialIcons]]
  name = "email"
  url = "mailto:josh.j.reynolds@gmail.com"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/joshjreynolds/"

[[menus.main]]
  name = "About"
  url = "/about"
  weight = 10

[[menus.main]]
  name = "Proficiencies"
  url = "/proficiencies"
  weight = 20


[params.label]
  text = "Josh Reynolds"
  icon = "/apple-touch-icon.png"
  iconHeight = 35
